In [7]:
import dask.dataframe as dd
from dask.diagnostics import ProgressBar 
from matplotlib import pyplot as plt 
df = dd.read_csv('./sales_06_FY2020-21.csv', dtype={'order_id': 'object'}) 
df

Dask DataFrame Structure:
              order_id order_date  status  item_id     sku qty_ordered    price    value discount_amount    total category payment_method   bi_st  cust_id   year   month ref_num Name Prefix First Name Middle Initial Last Name  Gender      age full_name  E Mail Customer Since     SSN Phone No.  Place Name  County    City   State    Zip  Region User Name Discount_Percent
npartitions=1
                object     object  object  float64  object     float64  float64  float64         float64  float64   object         object  object  float64  int64  object   int64      object     object         object    object  object  float64    object  object         object  object     object     object  object  object  object  int64  object    object          float64
                   ...        ...     ...      ...     ...         ...      ...      ...             ...      ...      ...            ...     ...      ...    ...     ...     ...         ...        ...            ...       ...     ...      ...       ...     ...            ...     ...        ...        ...     ...     ...     ...    ...     ...       ...              ...
Dask Name: read-csv, 1 graph layer

In [8]:
# Counting missing values in DF
missing_values = df.isnull().sum()
missing_values

Dask Series Structure:
npartitions=1
City    int64
year      ...
dtype: int64
Dask Name: dataframe-sum-agg, 4 graph layers

In [9]:
# Calculating the percent of missing values in DF
missing_count = ((missing_values / df.index.size) * 100)
missing_count

Dask Series Structure:
npartitions=1
City    float64
year        ...
dtype: float64
Dask Name: mul, 9 graph layers

In [10]:
# Computing the DAG
with ProgressBar():
  missing_count_pct = missing_count.compute()
missing_count_pct

[########################################] | 100% Completed | 2.85 ss

order_id            0.0
order_date          0.0
status              0.0
item_id             0.0
sku                 0.0
qty_ordered         0.0
price               0.0
value               0.0
discount_amount     0.0
total               0.0
category            0.0
payment_method      0.0
bi_st               0.0
cust_id             0.0
year                0.0
month               0.0
ref_num             0.0
Name Prefix         0.0
First Name          0.0
Middle Initial      0.0
Last Name           0.0
Gender              0.0
age                 0.0
full_name           0.0
E Mail              0.0
Customer Since      0.0
SSN                 0.0
Phone No.           0.0
Place Name          0.0
County              0.0
City                0.0
State               0.0
Zip                 0.0
Region              0.0
User Name           0.0
Discount_Percent    0.0
dtype: float64